[package]
name = "rust-snippets"
version = "0.1.0"
authors = ["Alessandro Donini <alessandro.donini.tech@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
